import "server-only";

export const MARKDOWN_CONTRACT_VERSION = "0.1.0";
export const MARKDOWN_PIPELINE_VERSION = "0.1.0";

export const markdownLimits = {
  maxBytes: 1024 * 1024,
  maxLineBytes: 32 * 1024,
  maxNodes: 25_000,
  maxDepth: 16,
  maxLinks: 1_000,
  maxDefinitions: 1_000,
  maxCodeBlockBytes: 256 * 1024,
  maxTables: 100,
  maxTableRows: 500,
  maxTableColumns: 32,
  maxTableCells: 10_000,
  maxLinkDestinationBytes: 2_048,
  maxLinkTitleCharacters: 256,
  maxCodeLanguageCharacters: 32,
  maxIssues: 100,
  workerTimeoutMs: 2_500,
  workerMaxOldGenerationMb: 64,
  workerMaxYoungGenerationMb: 16,
  workerStackMb: 4,
  maxConcurrentWorkers: 2,
  maxQueuedValidations: 8,
  workerQueueTimeoutMs: 2_500,
} as const;

export const allowedMdastNodeTypes = new Set([
  "root",
  "paragraph",
  "text",
  "heading",
  "thematicBreak",
  "blockquote",
  "list",
  "listItem",
  "emphasis",
  "strong",
  "delete",
  "inlineCode",
  "code",
  "break",
  "link",
  "linkReference",
  "definition",
  "table",
  "tableRow",
  "tableCell",
]);

export const allowedHastTags = new Set([
  "a",
  "blockquote",
  "br",
  "code",
  "del",
  "em",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hr",
  "li",
  "ol",
  "p",
  "pre",
  "strong",
  "table",
  "tbody",
  "td",
  "th",
  "thead",
  "tr",
  "ul",
]);

export const markdownDependencyVersions = {
  unified: "11.0.5",
  remarkParse: "11.0.0",
  remarkGfm: "4.0.1",
  remarkRehype: "11.1.2",
  rehypeSanitize: "6.0.0",
  ipaddrJs: "2.4.0",
} as const;

export const markdownValidationOrder = [
  "parent-size-precheck",
  "source-bytes",
  "source-encoding",
  "source-characters",
  "source-lines",
  "front-matter",
  "parse-mdast",
  "forbidden-syntax",
  "validate-mdast",
  "validate-links",
  "project-hast",
  "validate-hast",
  "sanitize-hast",
  "compare-hast",
  "build-document",
  "build-report",
] as const;
