export const auditActions = {
  adminBootstrapped: "ADMIN_BOOTSTRAPPED",
  adminSessionsRevokedAll: "ADMIN_SESSIONS_REVOKED_ALL",
  authorizationDenied: "AUTHORIZATION_DENIED",
  backupCreated: "BACKUP_CREATED",
  backupVerified: "BACKUP_VERIFIED",
  catalogAuthorizationDenied: "CATALOG_AUTHORIZATION_DENIED",
  catalogCategoryArchived: "CATALOG_CATEGORY_ARCHIVED",
  catalogCategoryCreated: "CATALOG_CATEGORY_CREATED",
  catalogCategoryRestored: "CATALOG_CATEGORY_RESTORED",
  catalogCategoryUpdated: "CATALOG_CATEGORY_UPDATED",
  catalogConflictDetected: "CATALOG_CONFLICT_DETECTED",
  catalogModuleArchived: "CATALOG_MODULE_ARCHIVED",
  catalogModuleCreated: "CATALOG_MODULE_CREATED",
  catalogModuleRestored: "CATALOG_MODULE_RESTORED",
  catalogModuleUpdated: "CATALOG_MODULE_UPDATED",
  catalogSubcategoryArchived: "CATALOG_SUBCATEGORY_ARCHIVED",
  catalogSubcategoryCreated: "CATALOG_SUBCATEGORY_CREATED",
  catalogSubcategoryRestored: "CATALOG_SUBCATEGORY_RESTORED",
  catalogSubcategoryUpdated: "CATALOG_SUBCATEGORY_UPDATED",
  catalogVersionApproved: "CATALOG_VERSION_APPROVED",
  catalogVersionCreated: "CATALOG_VERSION_CREATED",
  catalogVersionReturnedToDraft: "CATALOG_VERSION_RETURNED_TO_DRAFT",
  catalogVersionSubmitted: "CATALOG_VERSION_SUBMITTED",
  catalogVersionSuperseded: "CATALOG_VERSION_SUPERSEDED",
  catalogVersionUpdated: "CATALOG_VERSION_UPDATED",
  loginFailed: "LOGIN_FAILED",
  loginRateLimited: "LOGIN_RATE_LIMITED",
  loginSucceeded: "LOGIN_SUCCEEDED",
  logoutSucceeded: "LOGOUT_SUCCEEDED",
  sessionCreated: "SESSION_CREATED",
  sessionRevoked: "SESSION_REVOKED",
  restoreTestFailed: "RESTORE_TEST_FAILED",
  restoreTestSucceeded: "RESTORE_TEST_SUCCEEDED",
  secretRotationFailed: "SECRET_ROTATION_FAILED",
  secretRotationStarted: "SECRET_ROTATION_STARTED",
  secretRotationSucceeded: "SECRET_ROTATION_SUCCEEDED",
  totpEnabled: "TOTP_ENABLED",
  totpSetupStarted: "TOTP_SETUP_STARTED",
  totpVerificationFailed: "TOTP_VERIFICATION_FAILED",
} as const;

export type AuditAction = (typeof auditActions)[keyof typeof auditActions];

export type AuditOutcome = "failure" | "success";
